"""add research insider transactions table

Revision ID: 178a3aa6f225
Revises: fa5789a64cf5
Create Date: 2026-07-22 02:51:23.265708
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "178a3aa6f225"
down_revision: str | None = "fa5789a64cf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_insider_transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("insider_cik", sa.String(), nullable=False),
        sa.Column("insider_name", sa.String(), nullable=False),
        sa.Column("is_director", sa.Boolean(), nullable=False),
        sa.Column("is_officer", sa.Boolean(), nullable=False),
        sa.Column("is_ten_percent_owner", sa.Boolean(), nullable=False),
        sa.Column("officer_title", sa.String(), nullable=True),
        sa.Column("transaction_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_code", sa.String(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("shares", sa.Float(), nullable=False),
        sa.Column("price_per_share", sa.Float(), nullable=True),
        sa.Column("transaction_value", sa.Float(), nullable=True),
        sa.Column("acquired_disposed", sa.String(), nullable=False),
        sa.Column("shares_owned_after", sa.Float(), nullable=True),
        sa.Column("ownership_change_percent", sa.Float(), nullable=True),
        sa.Column("is_planned_sale", sa.Boolean(), nullable=False),
        sa.Column("footnote_text", sa.String(), nullable=True),
        sa.Column("filing_context", sa.String(), nullable=True),
        sa.Column("filing_accession_number", sa.String(), nullable=False),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_research_insider_transactions_insider_cik"),
        "research_insider_transactions",
        ["insider_cik"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_insider_transactions_issuer_id"),
        "research_insider_transactions",
        ["issuer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_insider_transactions_transaction_date"),
        "research_insider_transactions",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_research_insider_transactions_transaction_date"),
        table_name="research_insider_transactions",
    )
    op.drop_index(
        op.f("ix_research_insider_transactions_issuer_id"),
        table_name="research_insider_transactions",
    )
    op.drop_index(
        op.f("ix_research_insider_transactions_insider_cik"),
        table_name="research_insider_transactions",
    )
    op.drop_table("research_insider_transactions")
    # ### end Alembic commands ###
