"""add research issuer security master and provider claim tables

Revision ID: 2c4a6f1f40ac
Revises: d5ef2020051d
Create Date: 2026-07-21 20:49:18.913657
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2c4a6f1f40ac"
down_revision: str | None = "d5ef2020051d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_issuers",
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cik", sa.String(), nullable=True),
        sa.Column("primary_ticker", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("source_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("issuer_id"),
    )
    op.create_index(op.f("ix_research_issuers_cik"), "research_issuers", ["cik"], unique=True)
    op.create_index(
        op.f("ix_research_issuers_primary_ticker"),
        "research_issuers",
        ["primary_ticker"],
        unique=False,
    )
    op.create_table(
        "research_provider_claims",
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("cik", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    op.create_index(
        op.f("ix_research_provider_claims_issuer_id"),
        "research_provider_claims",
        ["issuer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_provider_claims_provider"),
        "research_provider_claims",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "research_raw_responses",
        sa.Column("raw_response_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("raw_response_id"),
    )
    op.create_table(
        "research_securities",
        sa.Column("security_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("security_id"),
    )
    op.create_index(
        op.f("ix_research_securities_issuer_id"), "research_securities", ["issuer_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_securities_ticker"), "research_securities", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_securities_ticker"), table_name="research_securities")
    op.drop_index(op.f("ix_research_securities_issuer_id"), table_name="research_securities")
    op.drop_table("research_securities")
    op.drop_table("research_raw_responses")
    op.drop_index(
        op.f("ix_research_provider_claims_provider"), table_name="research_provider_claims"
    )
    op.drop_index(
        op.f("ix_research_provider_claims_issuer_id"), table_name="research_provider_claims"
    )
    op.drop_table("research_provider_claims")
    op.drop_index(op.f("ix_research_issuers_primary_ticker"), table_name="research_issuers")
    op.drop_index(op.f("ix_research_issuers_cik"), table_name="research_issuers")
    op.drop_table("research_issuers")
    # ### end Alembic commands ###
