"""add memory records

Revision ID: 2e076dc218c5
Revises: c8b922403a16
Create Date: 2026-07-21 16:26:51.289622
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e076dc218c5"
down_revision: str | None = "c8b922403a16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_records",
        sa.Column("memory_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subject_key", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("supersedes_memory_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(op.f("ix_memory_records_status"), "memory_records", ["status"], unique=False)
    op.create_index(
        op.f("ix_memory_records_subject_key"), "memory_records", ["subject_key"], unique=False
    )
    op.create_index(op.f("ix_memory_records_user_id"), "memory_records", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_records_user_id"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_subject_key"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_status"), table_name="memory_records")
    op.drop_table("memory_records")
    # ### end Alembic commands ###
