"""phase26_voice_preparation

Revision ID: 4cedcd27f7b8
Revises: 828b1a984fe2
Create Date: 2026-07-22 06:31:35.264197
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4cedcd27f7b8"
down_revision: str | None = "828b1a984fe2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated): both tables already
    # have real historical rows (Phases 6/8 onward) — a NOT NULL column with
    # no default would fail against them. Values match the Python-side
    # Pydantic field defaults (ConfirmationMethod.READABLE, Channel.TEXT,
    # interrupted=False) exactly.
    op.add_column(
        "approval_decisions",
        sa.Column("confirmation_method", sa.String(), nullable=False, server_default="readable"),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("channel", sa.String(), nullable=False, server_default="text"),
    )
    op.add_column(
        "conversation_messages",
        sa.Column("interrupted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_messages", "interrupted")
    op.drop_column("conversation_messages", "channel")
    op.drop_column("approval_decisions", "confirmation_method")
    # ### end Alembic commands ###
