"""add projects domain tables

Revision ID: 5c5a4aaebb3b
Revises: e3a9da5ce684
Create Date: 2026-07-22 04:50:17.813922
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5c5a4aaebb3b"
down_revision: str | None = "e3a9da5ce684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_blockers",
        sa.Column("blocker_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("blocker_id"),
    )
    op.create_index(
        op.f("ix_project_blockers_project_id"), "project_blockers", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_blockers_status"), "project_blockers", ["status"], unique=False
    )
    op.create_table(
        "project_decisions",
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_context", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        op.f("ix_project_decisions_project_id"), "project_decisions", ["project_id"], unique=False
    )
    op.create_table(
        "project_goals",
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("goal_id"),
    )
    op.create_index(
        op.f("ix_project_goals_project_id"), "project_goals", ["project_id"], unique=False
    )
    op.create_table(
        "project_milestones",
        sa.Column("milestone_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("milestone_id"),
    )
    op.create_index(
        op.f("ix_project_milestones_project_id"), "project_milestones", ["project_id"], unique=False
    )
    op.create_table(
        "project_status_updates",
        sa.Column("status_update_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("status_update_id"),
    )
    op.create_index(
        op.f("ix_project_status_updates_project_id"),
        "project_status_updates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("milestone_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_project_tasks_milestone_id"), "project_tasks", ["milestone_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_tasks_project_id"), "project_tasks", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_project_tasks_status"), "project_tasks", ["status"], unique=False)
    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("document_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_project_tasks_status"), table_name="project_tasks")
    op.drop_index(op.f("ix_project_tasks_project_id"), table_name="project_tasks")
    op.drop_index(op.f("ix_project_tasks_milestone_id"), table_name="project_tasks")
    op.drop_table("project_tasks")
    op.drop_index(op.f("ix_project_status_updates_project_id"), table_name="project_status_updates")
    op.drop_table("project_status_updates")
    op.drop_index(op.f("ix_project_milestones_project_id"), table_name="project_milestones")
    op.drop_table("project_milestones")
    op.drop_index(op.f("ix_project_goals_project_id"), table_name="project_goals")
    op.drop_table("project_goals")
    op.drop_index(op.f("ix_project_decisions_project_id"), table_name="project_decisions")
    op.drop_table("project_decisions")
    op.drop_index(op.f("ix_project_blockers_status"), table_name="project_blockers")
    op.drop_index(op.f("ix_project_blockers_project_id"), table_name="project_blockers")
    op.drop_table("project_blockers")
    # ### end Alembic commands ###
