"""phase27_paper_trading_observation

Revision ID: 5d13b69d13f9
Revises: 4cedcd27f7b8
Create Date: 2026-07-22 07:01:53.776968
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5d13b69d13f9"
down_revision: str | None = "4cedcd27f7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_hypothetical_performance_samples",
        sa.Column("sample_id", sa.String(), nullable=False),
        sa.Column("trade_id", sa.String(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("gain_loss_percent", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("sample_id"),
    )
    op.create_index(
        op.f("ix_portfolio_hypothetical_performance_samples_trade_id"),
        "portfolio_hypothetical_performance_samples",
        ["trade_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_hypothetical_trades",
        sa.Column("trade_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("hypothetical_price", sa.Float(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("rationale_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_outcome", sa.String(), nullable=False),
        sa.Column("expected_horizon_days", sa.Integer(), nullable=False),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("review_note", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(
        op.f("ix_portfolio_hypothetical_trades_status"),
        "portfolio_hypothetical_trades",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_hypothetical_trades_symbol"),
        "portfolio_hypothetical_trades",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_hypothetical_trades_user_id"),
        "portfolio_hypothetical_trades",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_hypothetical_trades_user_id"), table_name="portfolio_hypothetical_trades"
    )
    op.drop_index(
        op.f("ix_portfolio_hypothetical_trades_symbol"), table_name="portfolio_hypothetical_trades"
    )
    op.drop_index(
        op.f("ix_portfolio_hypothetical_trades_status"), table_name="portfolio_hypothetical_trades"
    )
    op.drop_table("portfolio_hypothetical_trades")
    op.drop_index(
        op.f("ix_portfolio_hypothetical_performance_samples_trade_id"),
        table_name="portfolio_hypothetical_performance_samples",
    )
    op.drop_table("portfolio_hypothetical_performance_samples")
    # ### end Alembic commands ###
