"""phase24_system_monitors_alerts_evaluation_runs

Revision ID: 77dfbc4c290e
Revises: 5c5a4aaebb3b
Create Date: 2026-07-22 05:29:42.341063
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "77dfbc4c290e"
down_revision: str | None = "5c5a4aaebb3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_alerts",
        sa.Column("alert_id", sa.String(), nullable=False),
        sa.Column("monitor_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("monitor_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("dedup_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_during_quiet_hours", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index(
        op.f("ix_system_alerts_dedup_key"), "system_alerts", ["dedup_key"], unique=False
    )
    op.create_index(
        op.f("ix_system_alerts_monitor_id"), "system_alerts", ["monitor_id"], unique=False
    )
    op.create_index(op.f("ix_system_alerts_status"), "system_alerts", ["status"], unique=False)
    op.create_index(op.f("ix_system_alerts_user_id"), "system_alerts", ["user_id"], unique=False)
    op.create_table(
        "system_evaluation_runs",
        sa.Column("evaluation_id", sa.String(), nullable=False),
        sa.Column("monitor_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("monitor_type", sa.String(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("evaluation_id"),
    )
    op.create_index(
        op.f("ix_system_evaluation_runs_monitor_id"),
        "system_evaluation_runs",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_evaluation_runs_user_id"),
        "system_evaluation_runs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "system_monitor_definitions",
        sa.Column("monitor_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("monitor_type", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("quiet_hours_start_utc", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_end_utc", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("monitor_id"),
    )
    op.create_index(
        op.f("ix_system_monitor_definitions_monitor_type"),
        "system_monitor_definitions",
        ["monitor_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_monitor_definitions_user_id"),
        "system_monitor_definitions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_system_monitor_definitions_user_id"), table_name="system_monitor_definitions"
    )
    op.drop_index(
        op.f("ix_system_monitor_definitions_monitor_type"), table_name="system_monitor_definitions"
    )
    op.drop_table("system_monitor_definitions")
    op.drop_index(op.f("ix_system_evaluation_runs_user_id"), table_name="system_evaluation_runs")
    op.drop_index(op.f("ix_system_evaluation_runs_monitor_id"), table_name="system_evaluation_runs")
    op.drop_table("system_evaluation_runs")
    op.drop_index(op.f("ix_system_alerts_user_id"), table_name="system_alerts")
    op.drop_index(op.f("ix_system_alerts_status"), table_name="system_alerts")
    op.drop_index(op.f("ix_system_alerts_monitor_id"), table_name="system_alerts")
    op.drop_index(op.f("ix_system_alerts_dedup_key"), table_name="system_alerts")
    op.drop_table("system_alerts")
    # ### end Alembic commands ###
