"""initial schema

Revision ID: 7bcc3d9516b3
Revises:
Create Date: 2026-07-21 04:38:25.761367
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7bcc3d9516b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("audit_id", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("capability_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("approval_id", sa.String(), nullable=True),
        sa.Column("verification_status", sa.String(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_table(
        "computed_value_records",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("calculation_name", sa.String(), nullable=False),
        sa.Column("calculation_version", sa.String(), nullable=False),
        sa.Column("input_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rounding_policy", sa.String(), nullable=True),
        sa.Column("validation_result", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        op.f("ix_computed_value_records_calculation_name"),
        "computed_value_records",
        ["calculation_name"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("job_version", sa.Integer(), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("retry_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_classification", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_jobs_correlation_id"), "jobs", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_jobs_idempotency_key"), "jobs", ["idempotency_key"], unique=True)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "model_calls",
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("cost_estimate_usd", sa.Float(), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("escalation_reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        op.f("ix_model_calls_correlation_id"), "model_calls", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_model_calls_provider"), "model_calls", ["provider"], unique=False)
    op.create_table(
        "source_records",
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("request_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_hash", sa.String(), nullable=True),
        sa.Column("data_effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("freshness_policy_seconds", sa.Float(), nullable=True),
        sa.Column("raw_storage_ref", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("validation_status", sa.String(), nullable=False),
        sa.Column("error_state", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("record_id"),
    )
    op.create_index(
        op.f("ix_source_records_provider"), "source_records", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_source_records_source_type"), "source_records", ["source_type"], unique=False
    )
    op.create_table(
        "tool_calls",
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("capability_id", sa.String(), nullable=False),
        sa.Column("capability_version", sa.Integer(), nullable=False),
        sa.Column("permission_check_passed", sa.Boolean(), nullable=False),
        sa.Column("approval_check_passed", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("input_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        op.f("ix_tool_calls_capability_id"), "tool_calls", ["capability_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_calls_correlation_id"), "tool_calls", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_correlation_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_capability_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_source_records_source_type"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_provider"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_model_calls_provider"), table_name="model_calls")
    op.drop_index(op.f("ix_model_calls_correlation_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_idempotency_key"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_correlation_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        op.f("ix_computed_value_records_calculation_name"), table_name="computed_value_records"
    )
    op.drop_table("computed_value_records")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
