"""phase25_trust_dashboard_observability

Revision ID: 828b1a984fe2
Revises: 77dfbc4c290e
Create Date: 2026-07-22 06:02:29.807380
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "828b1a984fe2"
down_revision: str | None = "77dfbc4c290e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_hallucination_incidents",
        sa.Column("incident_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_note", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_system_hallucination_incidents_correlation_id"),
        "system_hallucination_incidents",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_hallucination_incidents_status"),
        "system_hallucination_incidents",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_hallucination_incidents_user_id"),
        "system_hallucination_incidents",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "system_regression_cases",
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("incorrect_output", sa.String(), nullable=False),
        sa.Column("corrected_output", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("case_id"),
    )
    op.create_index(
        op.f("ix_system_regression_cases_source_id"),
        "system_regression_cases",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_regression_cases_source_type"),
        "system_regression_cases",
        ["source_type"],
        unique=False,
    )
    op.add_column("model_calls", sa.Column("schema_valid", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_calls", "schema_valid")
    op.drop_index(
        op.f("ix_system_regression_cases_source_type"), table_name="system_regression_cases"
    )
    op.drop_index(
        op.f("ix_system_regression_cases_source_id"), table_name="system_regression_cases"
    )
    op.drop_table("system_regression_cases")
    op.drop_index(
        op.f("ix_system_hallucination_incidents_user_id"),
        table_name="system_hallucination_incidents",
    )
    op.drop_index(
        op.f("ix_system_hallucination_incidents_status"),
        table_name="system_hallucination_incidents",
    )
    op.drop_index(
        op.f("ix_system_hallucination_incidents_correlation_id"),
        table_name="system_hallucination_incidents",
    )
    op.drop_table("system_hallucination_incidents")
    # ### end Alembic commands ###
