"""add portfolio and schwab tables

Revision ID: c5cc4bddcf30
Revises: ddf1d17cc80b
Create Date: 2026-07-21 18:34:05.796046
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c5cc4bddcf30"
down_revision: str | None = "ddf1d17cc80b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_account_balances",
        sa.Column("balance_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("cash_balance", sa.Float(), nullable=True),
        sa.Column("schwab_reported_total", sa.Float(), nullable=True),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("balance_id"),
    )
    op.create_index(
        op.f("ix_portfolio_account_balances_account_id"),
        "portfolio_account_balances",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_account_balances_user_id"),
        "portfolio_account_balances",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_accounts",
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("account_hash", sa.String(), nullable=False),
        sa.Column("display_mask", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_portfolio_accounts_account_hash"),
        "portfolio_accounts",
        ["account_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_portfolio_accounts_user_id"), "portfolio_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "portfolio_positions",
        sa.Column("position_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("average_price", sa.Float(), nullable=True),
        sa.Column("market_value", sa.Float(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=True),
        sa.Column("day_change_dollar", sa.Float(), nullable=True),
        sa.Column("day_change_percent", sa.Float(), nullable=True),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("position_id"),
    )
    op.create_index(
        op.f("ix_portfolio_positions_account_id"),
        "portfolio_positions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_positions_user_id"), "portfolio_positions", ["user_id"], unique=False
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_market_value", sa.Float(), nullable=False),
        sa.Column("reconciled", sa.Boolean(), nullable=False),
        sa.Column("reconciliation_diff", sa.Float(), nullable=True),
        sa.Column("account_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_taken_at"), "portfolio_snapshots", ["taken_at"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_id"), "portfolio_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "schwab_credentials",
        sa.Column("credential_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("encrypted_access_token", sa.String(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("credential_id"),
    )
    op.create_index(
        op.f("ix_schwab_credentials_user_id"), "schwab_credentials", ["user_id"], unique=True
    )
    op.create_table(
        "schwab_raw_responses",
        sa.Column("raw_response_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("raw_response_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schwab_raw_responses")
    op.drop_index(op.f("ix_schwab_credentials_user_id"), table_name="schwab_credentials")
    op.drop_table("schwab_credentials")
    op.drop_index(op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_snapshots_taken_at"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_positions_user_id"), table_name="portfolio_positions")
    op.drop_index(op.f("ix_portfolio_positions_account_id"), table_name="portfolio_positions")
    op.drop_table("portfolio_positions")
    op.drop_index(op.f("ix_portfolio_accounts_user_id"), table_name="portfolio_accounts")
    op.drop_index(op.f("ix_portfolio_accounts_account_hash"), table_name="portfolio_accounts")
    op.drop_table("portfolio_accounts")
    op.drop_index(
        op.f("ix_portfolio_account_balances_user_id"), table_name="portfolio_account_balances"
    )
    op.drop_index(
        op.f("ix_portfolio_account_balances_account_id"), table_name="portfolio_account_balances"
    )
    op.drop_table("portfolio_account_balances")
    # ### end Alembic commands ###
