"""add approval proposals and decisions

Revision ID: ca48be532116
Revises: 7bcc3d9516b3
Create Date: 2026-07-21 15:10:19.238418
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ca48be532116"
down_revision: str | None = "7bcc3d9516b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_decisions",
        sa.Column("approval_id", sa.String(), nullable=False),
        sa.Column("proposal_id", sa.String(), nullable=False),
        sa.Column("payload_hash", sa.String(), nullable=False),
        sa.Column("approving_user_id", sa.String(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approval_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmation_challenge", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        op.f("ix_approval_decisions_proposal_id"),
        "approval_decisions",
        ["proposal_id"],
        unique=False,
    )
    op.create_table(
        "approval_proposals",
        sa.Column("proposal_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("action_type", sa.String(), nullable=False),
        sa.Column("action_schema_version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_system", sa.String(), nullable=False),
        sa.Column("expected_effect", sa.String(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("required_permission", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("validation_result", sa.String(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_context", sa.String(), nullable=True),
        sa.Column("payload_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    op.create_index(
        op.f("ix_approval_proposals_action_type"),
        "approval_proposals",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_proposals_status"), "approval_proposals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_approval_proposals_user_id"), "approval_proposals", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_proposals_user_id"), table_name="approval_proposals")
    op.drop_index(op.f("ix_approval_proposals_status"), table_name="approval_proposals")
    op.drop_index(op.f("ix_approval_proposals_action_type"), table_name="approval_proposals")
    op.drop_table("approval_proposals")
    op.drop_index(op.f("ix_approval_decisions_proposal_id"), table_name="approval_decisions")
    op.drop_table("approval_decisions")
    # ### end Alembic commands ###
