"""add portfolio ips and compliance tables

Revision ID: d5ef2020051d
Revises: c5cc4bddcf30
Create Date: 2026-07-21 19:57:48.499295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d5ef2020051d"
down_revision: str | None = "c5cc4bddcf30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_compliance_results",
        sa.Column("result_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("ips_version_id", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("compliant", sa.Boolean(), nullable=False),
        sa.Column("breaches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("result_id"),
    )
    op.create_index(
        op.f("ix_portfolio_compliance_results_evaluated_at"),
        "portfolio_compliance_results",
        ["evaluated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_compliance_results_ips_version_id"),
        "portfolio_compliance_results",
        ["ips_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_compliance_results_user_id"),
        "portfolio_compliance_results",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_ips_versions",
        sa.Column("version_id", sa.String(), nullable=False),
        sa.Column("ips_id", sa.String(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("account_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allocation_ranges", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("concentration_max_percent", sa.Float(), nullable=False),
        sa.Column("restricted_securities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        op.f("ix_portfolio_ips_versions_ips_id"), "portfolio_ips_versions", ["ips_id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_ips_versions_is_active"),
        "portfolio_ips_versions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_ips_versions_user_id"),
        "portfolio_ips_versions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_portfolio_ips_versions_user_id"), table_name="portfolio_ips_versions")
    op.drop_index(op.f("ix_portfolio_ips_versions_is_active"), table_name="portfolio_ips_versions")
    op.drop_index(op.f("ix_portfolio_ips_versions_ips_id"), table_name="portfolio_ips_versions")
    op.drop_table("portfolio_ips_versions")
    op.drop_index(
        op.f("ix_portfolio_compliance_results_user_id"), table_name="portfolio_compliance_results"
    )
    op.drop_index(
        op.f("ix_portfolio_compliance_results_ips_version_id"),
        table_name="portfolio_compliance_results",
    )
    op.drop_index(
        op.f("ix_portfolio_compliance_results_evaluated_at"),
        table_name="portfolio_compliance_results",
    )
    op.drop_table("portfolio_compliance_results")
    # ### end Alembic commands ###
