"""add calendar credentials and events

Revision ID: ddf1d17cc80b
Revises: 2e076dc218c5
Create Date: 2026-07-21 17:03:41.588939
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ddf1d17cc80b"
down_revision: str | None = "2e076dc218c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_credentials",
        sa.Column("credential_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("encrypted_access_token", sa.String(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("credential_id"),
    )
    op.create_index(
        op.f("ix_calendar_credentials_user_id"), "calendar_credentials", ["user_id"], unique=True
    )
    op.create_table(
        "calendar_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("provider_event_id", sa.String(), nullable=False),
        sa.Column("calendar_id", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_busy", sa.Boolean(), nullable=False),
        sa.Column("recurring_event_id", sa.String(), nullable=True),
        sa.Column("html_link", sa.String(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_calendar_events_end"), "calendar_events", ["end"], unique=False)
    op.create_index(
        op.f("ix_calendar_events_provider_event_id"),
        "calendar_events",
        ["provider_event_id"],
        unique=False,
    )
    op.create_index(op.f("ix_calendar_events_start"), "calendar_events", ["start"], unique=False)
    op.create_index(
        op.f("ix_calendar_events_user_id"), "calendar_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calendar_events_user_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_start"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_provider_event_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_end"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_calendar_credentials_user_id"), table_name="calendar_credentials")
    op.drop_table("calendar_credentials")
    # ### end Alembic commands ###
