"""add research politician transactions and committee assignments tables

Revision ID: e3a9da5ce684
Revises: 178a3aa6f225
Create Date: 2026-07-22 03:40:37.689955
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e3a9da5ce684"
down_revision: str | None = "178a3aa6f225"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_committee_assignments",
        sa.Column("politician_bioguide_id", sa.String(), nullable=False),
        sa.Column("committee_thomas_id", sa.String(), nullable=False),
        sa.Column("committee_name", sa.String(), nullable=False),
        sa.Column("chamber", sa.String(), nullable=False),
        sa.Column("jurisdiction_text", sa.String(), nullable=True),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("politician_bioguide_id", "committee_thomas_id"),
    )
    op.create_index(
        op.f("ix_research_committee_assignments_committee_thomas_id"),
        "research_committee_assignments",
        ["committee_thomas_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_committee_assignments_politician_bioguide_id"),
        "research_committee_assignments",
        ["politician_bioguide_id"],
        unique=False,
    )
    op.create_table(
        "research_politician_transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("politician_bioguide_id", sa.String(), nullable=True),
        sa.Column("politician_name", sa.String(), nullable=False),
        sa.Column("chamber", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("party", sa.String(), nullable=True),
        sa.Column("report_id", sa.String(), nullable=False),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("asset_name", sa.String(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("range_low", sa.Float(), nullable=False),
        sa.Column("range_high", sa.Float(), nullable=True),
        sa.Column("filing_delay_days", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_research_politician_transactions_politician_bioguide_id"),
        "research_politician_transactions",
        ["politician_bioguide_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_politician_transactions_report_id"),
        "research_politician_transactions",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_politician_transactions_ticker"),
        "research_politician_transactions",
        ["ticker"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_politician_transactions_transaction_date"),
        "research_politician_transactions",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_research_politician_transactions_transaction_date"),
        table_name="research_politician_transactions",
    )
    op.drop_index(
        op.f("ix_research_politician_transactions_ticker"),
        table_name="research_politician_transactions",
    )
    op.drop_index(
        op.f("ix_research_politician_transactions_report_id"),
        table_name="research_politician_transactions",
    )
    op.drop_index(
        op.f("ix_research_politician_transactions_politician_bioguide_id"),
        table_name="research_politician_transactions",
    )
    op.drop_table("research_politician_transactions")
    op.drop_index(
        op.f("ix_research_committee_assignments_politician_bioguide_id"),
        table_name="research_committee_assignments",
    )
    op.drop_index(
        op.f("ix_research_committee_assignments_committee_thomas_id"),
        table_name="research_committee_assignments",
    )
    op.drop_table("research_committee_assignments")
    # ### end Alembic commands ###
