"""add research news article digest and feedback tables

Revision ID: fa5789a64cf5
Revises: 2c4a6f1f40ac
Create Date: 2026-07-21 21:11:12.332202
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fa5789a64cf5"
down_revision: str | None = "2c4a6f1f40ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_news_articles",
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("headline", sa.String(), nullable=False),
        sa.Column("blurb", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_record_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column("is_cluster_primary", sa.Boolean(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("article_id"),
    )
    op.create_index(
        op.f("ix_research_news_articles_cluster_id"),
        "research_news_articles",
        ["cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_news_articles_issuer_id"),
        "research_news_articles",
        ["issuer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_news_articles_published_at"),
        "research_news_articles",
        ["published_at"],
        unique=False,
    )
    op.create_table(
        "research_news_digests",
        sa.Column("digest_id", sa.String(), nullable=False),
        sa.Column("issuer_id", sa.String(), nullable=False),
        sa.Column("article_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("digest_id"),
    )
    op.create_index(
        op.f("ix_research_news_digests_generated_at"),
        "research_news_digests",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_news_digests_issuer_id"),
        "research_news_digests",
        ["issuer_id"],
        unique=False,
    )
    op.create_table(
        "research_news_feedback",
        sa.Column("feedback_id", sa.String(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("useful", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        op.f("ix_research_news_feedback_article_id"),
        "research_news_feedback",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_news_feedback_user_id"),
        "research_news_feedback",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_news_feedback_user_id"), table_name="research_news_feedback")
    op.drop_index(op.f("ix_research_news_feedback_article_id"), table_name="research_news_feedback")
    op.drop_table("research_news_feedback")
    op.drop_index(op.f("ix_research_news_digests_issuer_id"), table_name="research_news_digests")
    op.drop_index(op.f("ix_research_news_digests_generated_at"), table_name="research_news_digests")
    op.drop_table("research_news_digests")
    op.drop_index(
        op.f("ix_research_news_articles_published_at"), table_name="research_news_articles"
    )
    op.drop_index(op.f("ix_research_news_articles_issuer_id"), table_name="research_news_articles")
    op.drop_index(op.f("ix_research_news_articles_cluster_id"), table_name="research_news_articles")
    op.drop_table("research_news_articles")
    # ### end Alembic commands ###
